version: "3"
services:
  offer-service:
    image: 'offer-service:latest'
    build:
      context: ./offer-service
    container_name: 'offer-service'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/landlord
      - SPRING_DATASOURCE_USERNAME=offer-service
      - SPRING_DATASOURCE_PASSWORD=!QAZ2wsx
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_GENERATE_DDL=false
    depends_on:
      - 'db'
    restart: on-failure
    #    deploy:
    #      restart_policy:
    #        condition: on-failure
    #        delay: 5s
    #        max_attempts: 3
    #        window: 60s
    ports:
      - "8080:8080"
  landlord-web:
    image: 'landlord-web:latest'
    container_name: 'landlord-web'
    build:
      context: ./landlord-web
    depends_on:
      - offer-service
    ports:
      - "3000:3000"
  db:
    image: 'postgres:13.1-alpine'
    container_name: 'db'
    environment:
      - POSTGRES_USER=offer-service
      - POSTGRES_PASSWORD=!QAZ2wsx
      - POSTGRES_DB=landlord
    volumes:
      - ./db/001_address-structure.sql:/docker-entrypoint-initdb.d/001_address-structure.sql
      - ./db/002_model-structure.sql:/docker-entrypoint-initdb.d/002_model-structure.sql
      - ./db/003_users-inits.sql:/docker-entrypoint-initdb.d/003_users-inits.sql
      - ./db/004_init-flats.sql:/docker-entrypoint-initdb.d/004_init-flats.sql
      - ./db/005_init-offers.sql:/docker-entrypoint-initdb.d/005_init-offers.sql