-- CREATE TABLE accounts
-- (
--     user_id    SERIAL PRIMARY KEY,
--     username   VARCHAR(50) UNIQUE  NOT NULL,
--     password   VARCHAR(50)         NOT NULL,
--     email      VARCHAR(255) UNIQUE NOT NULL,
--     created_on TIMESTAMP           NOT NULL
-- );
--
-- INSERT INTO accounts (username, password, email, created_on)
-- VALUES ('walczaq',
--         '!QAZ2wsx',
--         'walczak@email.com',
--         CURRENT_TIMESTAMP);